name: test
on: [push]

defaults:
  run:
    shell: sh

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: debian:testing
    steps:
    - uses: actions/checkout@v3
    - run: apt -y update
    - run: apt -y install g++-multilib libboost-dev make nasm yasm
    - run: make test
    - run: make -C sample CXXFLAGS="-DXBYAK_NO_EXCEPTION"
