name: Windows Binary Test

on:
  pull_request:
    branches: [main]
    paths:
      - ".github/workflows/windows-test.yml"
      - "requirements.txt"
      - "setup.py"
      - "neural_speed/**"
      - "bestla/**"
      - '!bestla/ut/**'
      - '!bestla/xbyak/**'
      - '!bestla/xbyak/*.md'
      - '!neural_speed/*.md'

  workflow_dispatch:

# If there is a new commit, the previous jobs will be canceled
concurrency:
    group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
    cancel-in-progress: true

env:
    SCRIPT_PATH: ${{ github.workspace }}\.github\workflows\scripts
    WORKING_DIR: ${{ github.workspace }}

jobs:
    Windows-Binary-Test:
      runs-on: 'Windows'
      steps:
        - name: Checkout out Repo
          uses: actions/checkout@v4
          with:
            submodules: "recursive"
            fetch-tags: true
            path: "a"

        - name: Binary build
          shell: cmd
          run: |
            SET HTTP_PROXY=http://proxy-dmz.intel.com:912
            SET HTTPS_PROXY=http://proxy-dmz.intel.com:912
            SET http_proxy=http://proxy-dmz.intel.com:912
            SET https_proxy=http://proxy-dmz.intel.com:912
            cd ${{ github.workspace }}\a\.github\workflows\scripts
            prepare_env_with_conda.bat
